[General]
# true, flase
ShowHidden = true

[Tabs]
Left = [ 'ListView:C:\User\ysun' ]
Right = [ 'ListView:C:\Users\ysun\Workspaces\Private\OneFileManager' ]


[Trace]
# 0 - None, 1 - Info, 2 - Warning, 3 - Error, 4 - Debug
Level = 4
# available variable: %APP_DIR%, // TODO  %CUR_USER_HOME%, %SYSTEM_ROOT%
File = '%APP_DIR%\log\ofm.log'
