[General]
# true, flase
ShowHidden = true

[Tabs]
Left = [ 'ListView:/Users/sunyanlin' ]
Right = [ 'ListView:/Users/sunyanlin/Documents/workspace/onefilemanager' ]


[Trace]
# error, warn, info, verbose, debug, silly
Level = 'debug'
# available variable: %APP_DIR%, // TODO  %CUR_USER_HOME%, %SYSTEM_ROOT%
File = "%APP_DIR%/log/ofm.log"
